### ISSUE TITLE
NP tarea 3

### ISSUE THREAD

**Issue by satuelisa** [chrismedrdz/Computer-Vision#2]
Andar fallando en las tareas antes de medio curso es un indicador bastante claro de reprobación probable... Ven a clase a aclarar dudas si no logras moverle a las tareas por tu cuenta.

**Comment by satuelisa** [comment]
También NP de la tarea 4. Avísame si te diste de baja para no perder tiempo revisando tu repositorio. Si tienes dudas de las tareas, ocupo que asistes a las clases.

**Comment by chrismedrdz** [comment]
Si.... Tengo dudas, prometo ya no faltar y ponerme al corriente con esas
dos tareas mas tardar este viernes.
