### ISSUE TITLE
Otro NP

### ISSUE THREAD

**Issue by satuelisa** [chrismedrdz/Computer-Vision#3]
Y siempre andas con tu rollo que "ahora sí te vas a poner a jalar"... No sé si te crees ni a ti mismo cuando lo dices.

**Comment by chrismedrdz** [comment]
Sigo jalando no he dormido y no fui a trabajar :(
Hoy en la tarde ya están las tres tareas arriba... De hecho ya esta la de
lineas pero las quería subir juntas :)

**Comment by satuelisa** [comment]
Pues, la calificación de hoy ya ha terminado. La siguiente será la última,
la mañana del día de entrega de la tarea 6. Después de eso ya no habrá
revisiones adicionales.

**Comment by chrismedrdz** [comment]
Cuente con ello, igual manera al rato las subo para que no quede duda que
estoy jalando en esto. No quiero dejar cosas para después y que valga la
pena lo que llevo aquí aprendido.
